#include "mod_types.h"

extern "C" {

/* --- lpf2.hub_type --- */
#define LPF2_REG_HUBTYPE(name) LPF2_REG(name, Lpf2::HubType::name)
LPF2_DEFINE_MOD_WITH_GLOB(hub_type,
    LPF2_REG_HUBTYPE(UNKNOWNHUB),
    LPF2_REG_HUBTYPE(BOOST_MOVE_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_REMOTE),
    LPF2_REG_HUBTYPE(DUPLO_TRAIN_HUB),
    LPF2_REG_HUBTYPE(CONTROL_PLUS_HUB),
    LPF2_REG_HUBTYPE(MARIO_HUB),
);

/* --- lpf2.device_type --- */
#define LPF2_REG_DEVTYPE(name) LPF2_REG(name, Lpf2::DeviceType::name)
LPF2_DEFINE_MOD_WITH_GLOB(device_type,
    LPF2_REG_DEVTYPE(UNKNOWNDEVICE),
    LPF2_REG_DEVTYPE(SIMPLE_MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TRAIN_MOTOR),
    LPF2_REG_DEVTYPE(LIGHT),
    LPF2_REG_DEVTYPE(VOLTAGE_SENSOR),
    LPF2_REG_DEVTYPE(CURRENT_SENSOR),
    LPF2_REG_DEVTYPE(PIEZO_BUZZER),
    LPF2_REG_DEVTYPE(HUB_LED),
    LPF2_REG_DEVTYPE(TILT_SENSOR),
    LPF2_REG_DEVTYPE(MOTION_SENSOR),
    LPF2_REG_DEVTYPE(COLOR_DISTANCE_SENSOR),
    LPF2_REG_DEVTYPE(MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(MOVE_HUB_MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(MOVE_HUB_TILT_SENSOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_MOTOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_SPEAKER),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_COLOR_SENSOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_SPEEDOMETER),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_XLARGE_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_ANGULAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_ANGULAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_GEST_SENSOR),
    LPF2_REG_DEVTYPE(REMOTE_CONTROL_BUTTON),
    LPF2_REG_DEVTYPE(REMOTE_CONTROL_RSSI),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_ACCELEROMETER),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_GYRO_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_TILT_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_TEMPERATURE_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_COLOR_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_DISTANCE_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_FORCE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_GESTURE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_BARCODE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_PANT_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_ANGULAR_MOTOR_GREY),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_ANGULAR_MOTOR_GREY),
);

/* --- lpf2.alerts --- */
#define LPF2_REG_ALERT(name) LPF2_REG(name, Lpf2::HubAlertType::name)
LPF2_DEFINE_MOD_WITH_GLOB(alerts, 
    LPF2_REG_ALERT(LOW_BATTERY),
    LPF2_REG_ALERT(HIGH_CURRENT),
    LPF2_REG_ALERT(LOW_SIGNAL_STRENGTH),
    LPF2_REG_ALERT(OVER_POWER_CONITION),
);

/* --- lpf2.battery_type --- */
#define LPF2_REG_BATT_TYPE(name) LPF2_REG(name, Lpf2::BatteryType::name)
LPF2_DEFINE_MOD_WITH_GLOB(battery_type, 
    LPF2_REG_BATT_TYPE(NORMAL),
    LPF2_REG_BATT_TYPE(RECHARGEABLE),
);

/* --- lpf2.button_state --- */
#define LPF2_REG_BUTTON_STATE(name) LPF2_REG(name, Lpf2::ButtonState::name)
LPF2_DEFINE_MOD_WITH_GLOB(button_state, 
    LPF2_REG_BUTTON_STATE(PRESSED),
    LPF2_REG_BUTTON_STATE(RELEASED),
    LPF2_REG_BUTTON_STATE(UP),
    LPF2_REG_BUTTON_STATE(DOWN),
    LPF2_REG_BUTTON_STATE(STOP),
);

/* --- lpf2.color --- */
#define LPF2_REG_COLOR(name) LPF2_REG(name, Lpf2::ColorIDX::name)
LPF2_DEFINE_MOD_WITH_GLOB(color, 
    LPF2_REG_COLOR(BLACK),
    LPF2_REG_COLOR(PINK),
    LPF2_REG_COLOR(PURPLE),
    LPF2_REG_COLOR(BLUE),
    LPF2_REG_COLOR(LIGHTBLUE),
    LPF2_REG_COLOR(CYAN),
    LPF2_REG_COLOR(GREEN),
    LPF2_REG_COLOR(YELLOW),
    LPF2_REG_COLOR(ORANGE),
    LPF2_REG_COLOR(RED),
    LPF2_REG_COLOR(WHITE),
    LPF2_REG_COLOR(NUM_COLORS),
    LPF2_REG_COLOR(NONE)
);

/* --- lpf2.port_num.controlplus --- */
#define LPF2_REG_CPHP(name) LPF2_REG(name, Lpf2::ControlPlusHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(controlplus, 
    LPF2_REG_CPHP(A),
    LPF2_REG_CPHP(B),
    LPF2_REG_CPHP(C),
    LPF2_REG_CPHP(D),
    LPF2_REG_CPHP(LED),
    LPF2_REG_CPHP(CURRENT),
    LPF2_REG_CPHP(VOLTAGE),
    LPF2_REG_CPHP(TEMP),
    LPF2_REG_CPHP(TEMP2),
    LPF2_REG_CPHP(ACCELEROMETER),
    LPF2_REG_CPHP(GYRO),
    LPF2_REG_CPHP(TILT),
    LPF2_REG_CPHP(GESTURE),
);

/* --- lpf2.port_num.duplotrain --- */
#define LPF2_REG_DPHP(name) LPF2_REG(name, Lpf2::DuploTrainHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(duplotrain, 
    LPF2_REG_DPHP(MOTOR),
    LPF2_REG_DPHP(LED),
    LPF2_REG_DPHP(SPEAKER),
    LPF2_REG_DPHP(COLOR),
    LPF2_REG_DPHP(SPEEDOMETER),
    LPF2_REG_DPHP(VOLTAGE),
);

/* --- lpf2.port_num.movehub --- */
#define LPF2_REG_MHP(name) LPF2_REG(name, Lpf2::MoveHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(movehub, 
    LPF2_REG_MHP(A),
    LPF2_REG_MHP(B),
    LPF2_REG_MHP(AB),
    LPF2_REG_MHP(C),
    LPF2_REG_MHP(D),
    LPF2_REG_MHP(LED),
    LPF2_REG_MHP(TILT),
    LPF2_REG_MHP(CURRENT),
    LPF2_REG_MHP(VOLTAGE),
);

/* --- lpf2.port_num.poweredup --- */
#define LPF2_REG_PUHP(name) LPF2_REG(name, Lpf2::PoweredUpHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(poweredup, 
    LPF2_REG_PUHP(A),
    LPF2_REG_PUHP(B),
    LPF2_REG_PUHP(LED),
    LPF2_REG_PUHP(CURRENT),
    LPF2_REG_PUHP(VOLTAGE),
);

/* --- lpf2.port_num.poweredupremote --- */
#define LPF2_REG_PURHP(name) LPF2_REG(name, Lpf2::PoweredUpRemoteHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(poweredupremote,
    LPF2_REG_PURHP(LEFT),
    LPF2_REG_PURHP(RIGHT),
    LPF2_REG_PURHP(LED),
    LPF2_REG_PURHP(VOLTAGE),
    LPF2_REG_PURHP(RSSI),
);

/* --- lpf2.port_num.mario --- */
#define LPF2_REG_MP(name) LPF2_REG(name, Lpf2::MarioHubPort::name)
LPF2_DEFINE_MOD_WITH_GLOB_STATIC(mario,
    LPF2_REG_MP(GESTURE),
    LPF2_REG_MP(BARCODE),
    LPF2_REG_MP(PANTS),
    LPF2_REG_MP(VOLTAGE),
);

/* --- lpf2.port_num --- */
LPF2_DEFINE_MOD_WITH_GLOB(port_num,
    LPF2_GET_LPF2_MOD_REG(controlplus),
    LPF2_GET_LPF2_MOD_REG(duplotrain),
    LPF2_GET_LPF2_MOD_REG(movehub),
    LPF2_GET_LPF2_MOD_REG(poweredup),
    LPF2_GET_LPF2_MOD_REG(poweredupremote),
    LPF2_GET_LPF2_MOD_REG(mario),
);

} // extern "C"