#include "mod_types.h"

extern "C" {

/* --- lpf2.hub_type --- */
#define LPF2_REG_HUBTYPE(name) LPF2_REG(name, Lpf2::HubType::name)
LPF2_DEFINE_MOD_WITH_GLOB(hub_type,
    LPF2_REG_HUBTYPE(UNKNOWNHUB),
    LPF2_REG_HUBTYPE(BOOST_MOVE_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_REMOTE),
    LPF2_REG_HUBTYPE(DUPLO_TRAIN_HUB),
    LPF2_REG_HUBTYPE(CONTROL_PLUS_HUB),
    LPF2_REG_HUBTYPE(MARIO_HUB),
);

/* --- lpf2.device_type --- */
#define LPF2_REG_DEVTYPE(name) LPF2_REG(name, Lpf2::DeviceType::name)
LPF2_DEFINE_MOD_WITH_GLOB(device_type,
    LPF2_REG_DEVTYPE(UNKNOWNDEVICE),
    LPF2_REG_DEVTYPE(SIMPLE_MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TRAIN_MOTOR),
    LPF2_REG_DEVTYPE(LIGHT),
    LPF2_REG_DEVTYPE(VOLTAGE_SENSOR),
    LPF2_REG_DEVTYPE(CURRENT_SENSOR),
    LPF2_REG_DEVTYPE(PIEZO_BUZZER),
    LPF2_REG_DEVTYPE(HUB_LED),
    LPF2_REG_DEVTYPE(TILT_SENSOR),
    LPF2_REG_DEVTYPE(MOTION_SENSOR),
    LPF2_REG_DEVTYPE(COLOR_DISTANCE_SENSOR),
    LPF2_REG_DEVTYPE(MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(MOVE_HUB_MEDIUM_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(MOVE_HUB_TILT_SENSOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_MOTOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_SPEAKER),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_COLOR_SENSOR),
    LPF2_REG_DEVTYPE(DUPLO_TRAIN_BASE_SPEEDOMETER),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_XLARGE_LINEAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_ANGULAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_ANGULAR_MOTOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_GEST_SENSOR),
    LPF2_REG_DEVTYPE(REMOTE_CONTROL_BUTTON),
    LPF2_REG_DEVTYPE(REMOTE_CONTROL_RSSI),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_ACCELEROMETER),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_GYRO_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_TILT_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_HUB_TEMPERATURE_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_COLOR_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_DISTANCE_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_FORCE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_GESTURE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_BARCODE_SENSOR),
    LPF2_REG_DEVTYPE(MARIO_HUB_PANT_SENSOR),
    LPF2_REG_DEVTYPE(TECHNIC_MEDIUM_ANGULAR_MOTOR_GREY),
    LPF2_REG_DEVTYPE(TECHNIC_LARGE_ANGULAR_MOTOR_GREY),
);

/* --- lpf2.color --- */
#define LPF2_REG_COLOR(name) LPF2_REG(name, Lpf2::ColorIDX::name)
LPF2_DEFINE_MOD_WITH_GLOB(color, 
    LPF2_REG_COLOR(BLACK),
    LPF2_REG_COLOR(PINK),
    LPF2_REG_COLOR(PURPLE),
    LPF2_REG_COLOR(BLUE),
    LPF2_REG_COLOR(LIGHTBLUE),
    LPF2_REG_COLOR(CYAN),
    LPF2_REG_COLOR(GREEN),
    LPF2_REG_COLOR(YELLOW),
    LPF2_REG_COLOR(ORANGE),
    LPF2_REG_COLOR(RED),
    LPF2_REG_COLOR(WHITE),
    LPF2_REG_COLOR(NUM_COLORS),
    LPF2_REG_COLOR(NONE)
);

} // extern "C"