#include "mod_types.h"

extern "C" {

/* --- lpf2.hub_type --- */
#define LPF2_REG_HUBTYPE(name) LPF2_REG(name, Lpf2::HubType::name)
LPF2_DEFINE_MOD_WITH_GLOB(hub_type,
    LPF2_REG_HUBTYPE(UNKNOWNHUB),
    LPF2_REG_HUBTYPE(BOOST_MOVE_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_HUB),
    LPF2_REG_HUBTYPE(POWERED_UP_REMOTE),
    LPF2_REG_HUBTYPE(DUPLO_TRAIN_HUB),
    LPF2_REG_HUBTYPE(CONTROL_PLUS_HUB),
    LPF2_REG_HUBTYPE(MARIO_HUB),
);

/* --- lpf2.Color --- */
#define LPF2_REG_COLOR(name) LPF2_REG(name, Lpf2::ColorIDX::name)
LPF2_DEFINE_MOD_WITH_GLOB(color, 
    LPF2_REG_COLOR(BLACK),
    LPF2_REG_COLOR(PINK),
    LPF2_REG_COLOR(PURPLE),
    LPF2_REG_COLOR(BLUE),
    LPF2_REG_COLOR(LIGHTBLUE),
    LPF2_REG_COLOR(CYAN),
    LPF2_REG_COLOR(GREEN),
    LPF2_REG_COLOR(YELLOW),
    LPF2_REG_COLOR(ORANGE),
    LPF2_REG_COLOR(RED),
    LPF2_REG_COLOR(WHITE),
    LPF2_REG_COLOR(NUM_COLORS),
    LPF2_REG_COLOR(NONE)
);

} // extern "C"