from __future__ import annotations
from lpf2 import port as _port

def registerDefault() -> None: ...

class basic_motor:
    def startPower(self, pw: int) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class encoder_motor:
    def startPower(self, pw: int) -> None: ...
    def setAccTime(self, time: int, profile: int) -> None: ...
    def setDecTime(self, time: int, profile: int) -> None: ...
    def startSpeed(self, speed: int = 100, maxPower: int = 100, useProfile: int = 0) -> None: ...
    def startSpeedForTime(self, time: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def startSpeedForDegrees(self, degrees: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def gotoAbsPosition(self, absPos: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def presetEncoder(self, pos: int) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class color_sensor:
    def getColorIdx(self) -> int: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class distance_sensor:
    def setLight(self, l1: int, l2: int, l3: int, l4: int) -> None: ...
    def getDistance(self) -> float: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class port_expander:
    def getPort(self, port_num: int) -> _port: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...
