from __future__ import annotations
from lpf2 import port as _port

def registerDefault() -> None: ...

class basic_motor:
    def startPower(self, pw: int) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class encoder_motor:
    def startPower(self, pw: int) -> None: ...
    def setAccTime(self, time: int, profile: int) -> None: ...
    def setDecTime(self, time: int, profile: int) -> None: ...
    def startSpeed(self, speed: int = 100, maxPower: int = 100, useProfile: int = 0) -> None: ...
    def startSpeedForTime(self, time: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def startSpeedForDegrees(self, degrees: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def gotoAbsPosition(self, absPos: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def presetEncoder(self, pos: int) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class color_sensor:
    MODE_COLOR: int = 0
    MODE_REFLT: int = 1
    MODE_AMBI: int = 2
    MODE_LIGHT: int = 3
    MODE_RGB: int = 5
    MODE_HSV: int = 6
    def getColorIdx(self) -> int: ...
    def getReflectivity(self) -> float: ...
    def getRGB(self) -> tuple[int, int, int, int]: ...
    def getHSV(self) -> tuple[int, int, int]: ...
    def setLight(self, l1: int, l2: int, l3: int) -> None: ...
    def setMode(self, modeNum: int, delta: float = 1.0) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class distance_sensor:
    MODE_LIGHT: int = 5
    def setLight(self, l1: int, l2: int, l3: int, l4: int) -> None: ...
    def getDistance(self) -> float: ...
    def setMode(self, modeNum: int, delta: float = 1.0) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class color_distance_sensor:
    MODE_COLOR: int = 0
    MODE_DIST: int = 1
    MODE_REFLT: int = 3
    MODE_AMBI: int = 4
    MODE_LED: int = 5
    MODE_RGB: int = 6
    MODE_IR: int = 7
    def getColorIdx(self) -> int: ...
    def getDistance(self) -> float: ...
    def getReflectedLight(self) -> int: ...
    def getAmbientLight(self) -> int: ...
    def getRgb(self) -> tuple[int, int, int]: ...
    def setIrTx(self, value: int) -> None: ...
    def setLedColor(self, color: int) -> None: ...
    def setMode(self, modeNum: int, delta: float = 1.0) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class hub_led:
    def setColorIdx(self, color: int) -> None: ...
    def setColor(self, r: int, g: int, b: int) -> None: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class accelerometer:
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class gyroscope:
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...

class port_expander:
    def getPort(self, port_num: int) -> _port: ...
    def getDeviceType(self) -> int: ...
    def name(self) -> str: ...
