from __future__ import annotations
from typing import Optional, Sequence, Union
from lpf2 import port_num as port_num
from lpf2 import hub_type as hub_type
from lpf2 import device_type as device_type
from lpf2 import alerts as alerts
from lpf2 import battery_type as battery_type
from lpf2 import button_state as button_state
from lpf2 import color as color
from lpf2 import local as local
from lpf2 import virtual as virtual
from lpf2 import devices as devices
from lpf2 import port_expander as port_expander
from typing import Callable

class battery:
    @staticmethod
    def setMaxVoltage(mv: int) -> None: ...
    @staticmethod
    def setMinVoltage(mv: int) -> None: ...
    @staticmethod
    def getMaxVoltage() -> int: ...
    @staticmethod
    def getMinVoltage() -> int: ...
    @staticmethod
    def setCurrentVoltage(mv: int) -> None: ...
    @staticmethod
    def getCurrentVoltage() -> int: ...
    @staticmethod
    def getPercent() -> int: ...
    @staticmethod
    def setPercentFunc(fn: Optional[Callable[[int, int, int], int]]) -> None: ...
    @staticmethod
    def setupAdcDivider(
        adc_channel: int,
        adc_unit: int,
        r_top_ohms: float,
        r_bottom_ohms: float,
        vref_mv: int = 3300,
        samples: int = 8,
    ) -> bool: ...
    @staticmethod
    def readBatteryVoltage() -> int: ...

class _motor_settings:
    id: int
    rated_max_speed: int
    max_voltage_mv: int
    speed_ksp: float
    speed_ksi: float
    speed_int_clamp: float
    speed_deadband_pct: float
    pos_kp: float
    pos_ki: float
    pos_kd: float
    pos_int_clamp: float
    pos_deadband_deg: float
    pos_decel_mdps2: float
    breakaway_pct: float
    kinetic_floor_pct: float

class motor_setting:
    medium_linear: _motor_settings
    technic_large_linear: _motor_settings
    technic_xlarge_linear: _motor_settings
    technic_medium_angular: _motor_settings
    technic_large_angular: _motor_settings
    technic_medium_angular_grey: _motor_settings
    technic_large_angular_grey: _motor_settings

class mode:
    name: str
    min: float
    max: float
    PCTmin: float
    PCTmax: float
    SImin: float
    SImax: float
    inMapping: int
    outMapping: int
    dataSets: int
    format: int
    figures: int
    decimals: int
    motorBias: int
    flags: int
    rawData: bytes

class version:
    Build: int
    Major: int
    Minor: int
    Bugfix: int

class port:
    def init(self) -> None: ...
    def update(self) -> None: ...
    def device(self) -> Union[
        devices.basic_motor,
        devices.encoder_motor,
        devices.color_sensor,
        devices.distance_sensor,
        devices.port_expander,
        None,
    ]: ...
    def writeData(self, mode: int, buf: bytes) -> int: ...
    def startPower(self, pw: int) -> None: ...
    def setAccTime(self, time: int, profile: int) -> None: ...
    def setDecTime(self, time: int, profile: int) -> None: ...
    def startSpeed(self, speed: int = 100, maxPower: int = 100, useProfile: int = 0) -> None: ...
    def startSpeedForTime(self, time: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def startSpeedForDegrees(self, degrees: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def gotoAbsPosition(self, absPos: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def presetEncoder(self, pos: int) -> None: ...
    def setRgbColorIdx(self, idx: int) -> None: ...
    def setRgbColor(self, r: int, g: int, b: int) -> None: ...
    def setMode(self, mode: int, delta: float = 1.0) -> int: ...
    def setModeCombo(self, idx: int, deltas: Sequence[float] = ()) -> int: ...
    def isDeviceConnected(self) -> bool: ...
    def getValue(self, mode: int, dataSet: int) -> float: ...
    def getValueStr(self, mode: int) -> str: ...
    def getDeviceType(self) -> int: ...
    def getModeCount(self) -> int: ...
    def getViewCount(self) -> int: ...
    def getMode(self, num: int) -> Optional[mode]: ...
    def getModeComboCount(self) -> int: ...
    def getModeCombo(self, combo: int) -> int: ...
    def getInputModes(self) -> int: ...
    def getOutputModes(self) -> int: ...
    def getCapabilities(self) -> int: ...
    def getInfoStr(self) -> str: ...
    def speedToRaw(self, speed: int) -> int: ...
    def rawToSpeed(self, raw: int) -> int: ...

class device_descriptor:
    modes: list[mode]
    fwVersion: version
    hwVersion: version

class hub_emulation:
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def setUseBuiltInDevices(self, use: bool) -> None: ...
    def setBatteryLevel(self, level: int) -> None: ...
    def setBatteryType(self, type: int) -> None: ...
    def setName(self, name: str) -> None: ...
    def setFirmwareVersion(self, v: version) -> None: ...
    def setHardwareVersion(self, v: version) -> None: ...
    def setButtonState(self, state: int) -> None: ...
    def setAlert(self, alert: int, on: bool) -> None: ...
    def getName(self) -> str: ...
    def attachPort(self, port_num: int, p: port) -> None: ...
