from __future__ import annotations

ADVERTISING_NAME: int = 0x01
BUTTON: int = 0x02
FW_VERSION: int = 0x03
HW_VERSION: int = 0x04
RSSI: int = 0x05
BATTERY_VOLTAGE: int = 0x06
BATTERY_TYPE: int = 0x07
MANUFACTURER_NAME: int = 0x08
RADIO_FIRMWARE_VERSION: int = 0x09
LEGO_WIRELESS_PROTOCOL_VERSION: int = 0x0A
SYSTEM_TYPE_ID: int = 0x0B
HW_NETWORK_ID: int = 0x0C
PRIMARY_MAC_ADDRESS: int = 0x0D
SECONDARY_MAC_ADDRESS: int = 0x0E
HARDWARE_NETWORK_FAMILY: int = 0x0F
