from __future__ import annotations
from typing import Sequence
from lpf2 import port as _port
from lpf2 import device_descriptor

class port(_port):
    def attachDevice(self, device: device) -> None: ...
    def detachDevice(self) -> None: ...

class device:
    def setModeData(self, mode: int, buf: bytes) -> None: ...
    def setWriteDataCallback(self, cb: object) -> None: ...
    def startPower(self, pw: int) -> None: ...
    def setAccTime(self, time: int, profile: int) -> None: ...
    def setDecTime(self, time: int, profile: int) -> None: ...
    def startSpeed(self, speed: int = 100, maxPower: int = 100, useProfile: int = 0) -> None: ...
    def startSpeedForTime(self, time: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def startSpeedForDegrees(self, degrees: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def gotoAbsPosition(self, absPos: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def presetEncoder(self, pos: int) -> None: ...
    def writeData(self, mode: int, buf: bytes) -> int: ...
    def setMode(self, mode: int, delta: float = 1.0) -> int: ...
    def setModeCombo(self, idx: int, deltas: Sequence[float] = ()) -> int: ...
    def __init__(self, descriptor: device_descriptor) -> None: ...
