from lpf2 import port as _port
from lpf2 import mode
from typing import Optional, Sequence

class port(_port):
    """Local port — same interface as lpf2.port, used for hub.ports."""
    def writeData(self, mode: int, buf: bytes) -> int: ...
    def startPower(self, pw: int) -> None: ...
    def setAccTime(self, time: int, profile: int) -> None: ...
    def setDecTime(self, time: int, profile: int) -> None: ...
    def startSpeed(self, speed: int = 100, maxPower: int = 100, useProfile: int = 0) -> None: ...
    def startSpeedForTime(self, time: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def startSpeedForDegrees(self, degrees: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def gotoAbsPosition(self, absPos: int, speed: int = 100, maxPower: int = 100, endState: int = 0, useProfile: int = 0) -> None: ...
    def presetEncoder(self, pos: int) -> None: ...
    def setRgbColorIdx(self, idx: int) -> None: ...
    def setRgbColor(self, r: int, g: int, b: int) -> None: ...
    def setMode(self, mode: int, delta: float = 1.0) -> int: ...
    def setModeCombo(self, idx: int, deltas: Sequence[float] = ()) -> int: ...
    def isDeviceConnected(self) -> bool: ...
    def getValue(self, mode: int, dataSet: int) -> float: ...
    def getValueStr(self, mode: int) -> str: ...
    def getDeviceType(self) -> int: ...
    def getModeCount(self) -> int: ...
    def getViewCount(self) -> int: ...
    def getMode(self, num: int) -> Optional[mode]: ...
    def getModeComboCount(self) -> int: ...
    def getModeCombo(self, combo: int) -> int: ...
    def getInputModes(self) -> int: ...
    def getOutputModes(self) -> int: ...
    def getCapabilities(self) -> int: ...
    def getInfoStr(self) -> str: ...
    def speedToRaw(self, speed: int) -> int: ...
    def rawToSpeed(self, raw: int) -> int: ...
